/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: maijing
 * Time: 2024-02-06 23:21:10
**/
#[allow(unused_imports)]
use std::cmp::{max, min};
use std::io::{stdin, stdout, BufWriter, Write};

#[derive(Default)]
struct Scanner {
    buffer: Vec<String>,
}
impl Scanner {
    fn next<T: std::str::FromStr>(&mut self) -> T {
        loop {
            if let Some(token) = self.buffer.pop() {
                return token.parse().ok().expect("Failed parse");
            }
            let mut input = String::new();
            stdin().read_line(&mut input).expect("Failed read");
            self.buffer = input.split_whitespace().rev().map(String::from).collect();
        }
    }
}

#[allow(dead_code)]
struct Random {
    state: usize,
}

impl Random {
    fn next(&mut self) -> usize {
        let mut x = self.state;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.state = x;
        x
    }

    #[allow(dead_code)]
    fn next_in_range(&mut self, from: usize, to: usize) -> usize {
        assert!(from < to);
        from + self.next() % (to - from)
    }

    #[allow(dead_code)]
    fn next_double(&mut self) -> f64 {
        (self.next() as f64) / (std::usize::MAX as f64)
    }

    #[allow(dead_code)]
    fn new(seed: usize) -> Self {
        assert_ne!(seed, 0);
        Self { state: seed }
    }
}

fn main() {
    let mut scan = Scanner::default();
    let out = &mut BufWriter::new(stdout());

    let t = scan.next::<usize>();
    for _ in 0..t {
        let n = scan.next::<usize>();
        let m = scan.next::<usize>();
        let k = scan.next::<usize>();
        let a = (0..n).map(|_| scan.next::<usize>()).collect::<Vec<_>>();
        let b = (0..m).map(|_| scan.next::<usize>()).collect::<Vec<_>>();
        let mut ta = vec![0; k + 1];
        let mut tb = vec![0; k + 1];
        for v in a {
            if v <= k {
                ta[v] = 1;
            }
        }
        for v in b {
            if v <= k {
                tb[v] = 1;
            }
        }
        let (mut sa, mut sb) = (0, 0);
        let mut both_zero = 0;
        for i in 1..=k {
            if ta[i] == 1 && tb[i] == 0 {
                sa += 1;
            }
            if ta[i] == 0 && tb[i] == 1 {
                sb += 1;
            }
            if ta[i] ==0 && tb[i] == 0 {
                both_zero = 1;
            }
        }
        if sa <= k / 2 && sb <= k / 2 && both_zero == 0{
            writeln!(out, "YES").ok();
        } else {
            writeln!(out, "NO").ok();
        }
    }
}
