/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: maijing
 * Time: 2024-02-06 22:56:17
**/
#[allow(unused_imports)]
use std::cmp::{max, min};
use std::io::{stdin, stdout, BufWriter, Write};

#[derive(Default)]
struct Scanner {
    buffer: Vec<String>,
}
impl Scanner {
    fn next<T: std::str::FromStr>(&mut self) -> T {
        loop {
            if let Some(token) = self.buffer.pop() {
                return token.parse().ok().expect("Failed parse");
            }
            let mut input = String::new();
            stdin().read_line(&mut input).expect("Failed read");
            self.buffer = input.split_whitespace().rev().map(String::from).collect();
        }
    }
}

#[allow(dead_code)]
struct Random {
    state: usize,
}

impl Random {
    fn next(&mut self) -> usize {
        let mut x = self.state;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.state = x;
        x
    }

    #[allow(dead_code)]
    fn next_in_range(&mut self, from: usize, to: usize) -> usize {
        assert!(from < to);
        from + self.next() % (to - from)
    }

    #[allow(dead_code)]
    fn next_double(&mut self) -> f64 {
        (self.next() as f64) / (std::usize::MAX as f64)
    }

    #[allow(dead_code)]
    fn new(seed: usize) -> Self {
        assert_ne!(seed, 0);
        Self { state: seed }
    }
}

fn main() {
    let mut scan = Scanner::default();
    let out = &mut BufWriter::new(stdout());

    let t = scan.next::<usize>();
    for _ in 0..t {
        let n = scan.next::<usize>();
        let a: Vec<usize> = (0..n).map(|_| scan.next::<usize>()).collect();
        let mut cur_char: char = 'a';
        let mut ans: Vec<char> = vec![' '; n];
        let mut ques: Vec<Vec<char>> = vec![Vec::new(); n];
        for (i, v) in a.iter().enumerate().rev() {
            if ques[*v].len() == 0 {
                ans[i] = cur_char;
                if *v != 0 {
                    ques[*v - 1].push(cur_char);
                }
                cur_char = char::from_u32(cur_char as u32 + 1).unwrap();
            } else {
                let c = ques[*v].pop().unwrap();
                ans[i] = c;
                if *v != 0 {
                    ques[*v - 1].push(c);
                }
            }
        }
        let ans_s = ans.iter().collect::<String>();
        writeln!(out, "{}", ans_s).ok();
    }
}
